### ISSUE TITLE
Can you provide trained GAN network .pt weight files?

### ISSUE THREAD

**Issue by shawa11111** [AI4HealthUOL/SSSD-ECG#12]
Hi, I am trying to generate ECG signals in two GAN networks. Can you provide the trained GAN network .pt weights file or the npy file of the ECG signals generated by the GAN networks?

**Comment by juanlopezcode** [comment]
Hi
Unfortunately, I'm unable to provide the trained GAN network weights or the npy files of the generated ECG signals at this time.
However, if you have any specific questions about the implementation or need guidance on how to train your own GAN networks for ECG signal generation, feel free to ask
Best
Juan
