### ISSUE TITLE
DIffusion hyperparameters

### ISSUE THREAD

**Issue by gabrielvc** [AI4HealthUOL/SSSD-ECG#15]
Hi, 

As far as i'm concerned, there is an issue with the current diffusion hyperparameters defined in the config file.
Running the current parameters for `T=200` yield an `sqrt(alpha_bar)` of approximately 0.4, which is of course far from the Gaussian, which would be equivalent to `sqrt(alpha_bar)` of approximately 0.01 or something really small.
I guess this is why I can't generate ECGs using the generate function, even if my trained loss is extremely small.
Indeed, the network is able to denoise moderately noisy ecgs but generation still don't work.

Furthermore, I could not find in your paper the hyperparameters you used in the diffusion training.
I would really like to be able to reproduce your work, but for the moment it is really challenging.

**Comment by hayaalsh** [comment]
Their trained model works. $\sqrt{\bar{\alpha}}$ takes values approximately between 0.35 and 1, depending on the diffusion step. Generation requires looping over all diffusion steps; it is not a one-step process, even with the acceleration described in the original DiffWave paper. Make sure to use the generation code [here](https://github.com/AI4HealthUOL/SSSD-ECG/blob/main/src/sssd/inference.py).

All hyperparameters are provided [here](https://github.com/AI4HealthUOL/SSSD-ECG/blob/main/src/sssd/config/config_SSSD_ECG.json).

**Comment by juanlopezcode** [comment]
Hi, 
The network should run with the provided diffusion hyperparameters, we mentioned them in the appendix of our paper, but they are also under the config file in this repo: https://github.com/AI4HealthUOL/SSSD-ECG/blob/main/src/sssd/config/config_SSSD_ECG.json

Follow the train.py and inference.py files under the following directory, these should be your unique files to run once dataset is located (don't update diffusion hyperparameters): [SSSD-ECG](https://github.com/AI4HealthUOL/SSSD-ECG/tree/main)/[src](https://github.com/AI4HealthUOL/SSSD-ECG/tree/main/src)
/sssd/

I hope this helps
Best
Juan
