### ISSUE TITLE
which leads each index from 1 to 12 corresponds to?

### ISSUE THREAD

**Issue by Ssw2001** [AI4HealthUOL/SSSD-ECG#16]
The shape of the dataset you provided, test_ptbxl_1000.npy, is (2203, 12, 1000). I would like to inquire about which leads each index from 1 to 12 corresponds to?  thank you!

**Comment by hayaalsh** [comment]
The PTB-XL dataset uses the following lead order: ['I', 'II', 'III', 'AVR', 'AVL', 'AVF', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6']. Note that the order listed on the [original dataset website](https://physionet.org/content/ptb-xl/1.0.3/) is incorrect; they switch 'AVR' and 'AVL'.

**Comment by juanlopezcode** [comment]
Hi, if you are using the ecg_data_preprocessing.ipynb file to extract the data, then you get the order of ['I','II','V1',...,'V6','III','AVR','AVL','AVF']. Otherwise, if you processed the data directly from physionet, you get the standard ['I', 'II', 'III', 'AVR', 'AVL', 'AVF', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6'] mentioned in the previous comment, I hope this helps
Best
Juan

**Comment by hayaalsh** [comment]
How about the synthetic data generated by the model? Does it follow ['I','II','V1',...,'V6','III','AVR','AVL','AVF'] as well?

**Comment by Ssw2001** [comment]
> Hi, if you are using the ecg_data_preprocessing.ipynb file to extract the data, then you get the order of ['I','II','V1',...,'V6','III','AVR','AVL','AVF']. Otherwise, if you processed the data directly from physionet, you get the standard ['I', 'II', 'III', 'AVR', 'AVL', 'AVF', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6'] mentioned in the previous comment, I hope this helps Best Juan

Thank you for your reply !     i directly used the  test_ptbxl_1000.npy and the train_ptbxl_1000.npy from https://mega.nz/folder/kT91jYpI#97GyTkVVUk97fzs1Oy4nBQ/folder/sW8UiBpT you provide  as my data, do the  test_ptbxl_1000.npy and the train_ptbxl_1000.npy  both follow the order  ['I', 'II', 'III', 'AVR', 'AVL', 'AVF', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6'] or ['I','II','V1',...,'V6','III','AVR','AVL','AVF']?  this is very important to me,thank you!

**Comment by juanlopezcode** [comment]
['I','II','V1',...,'V6','III','AVR','AVL','AVF']
