### ISSUE TITLE
how many  iters did you run?

### ISSUE THREAD

**Issue by Ssw2001** [AI4HealthUOL/SSSD-ECG#17]
"train_config": {
        "output_directory": "sssd_label_cond",
        "ckpt_iter": "max",
        "iters_per_ckpt": 4000,
        "iters_per_logging": 100,
        "n_iters": 100000,
        "learning_rate": 2e-4,
        "batch_size":8
hi, i'm sorry bothering you again. this is the part of your file : SSSD-ECG/src/sssd/config/config_SSSD_ECG.json, Should i  have to run 100000 iters or i can run less? I'm looking forward to your reply.
Best regards,

**Comment by juanlopezcode** [comment]
hi,
sorry late reply, I did 100000, you can of course try more or less based on your needs (I guess you must be measuring something for that?)
