### ISSUE TITLE
Data Loader

### ISSUE THREAD

**Issue by elizczimm** [AI4HealthUOL/SSSD-ECG#2]
https://github.com/AI4HealthUOL/SSSD-ECG/blob/d82aa2e4a207cf2c3211dd4c41c34a5aec7f61db/src/sssd/train.py#L81

How should the data be formatted?

**Comment by juanlopezcode** [comment]
hello, the numpy file should be [samples,channels,length], and you can get the data from here: https://mega.nz/folder/kT91jYpI#97GyTkVVUk97fzs1Oy4nBQ/folder/sW8UiBpT

**Comment by elizczimm** [comment]
Thanks for your help! I didn't see files for labels referenced on line 81 -- are they generated separately? And what should their format be? 

https://github.com/AI4HealthUOL/SSSD-ECG/blob/d82aa2e4a207cf2c3211dd4c41c34a5aec7f61db/src/sssd/train.py#L82

**Comment by juanlopezcode** [comment]
Hello @elizczimm, the format of the label set would be [samples,labels], I have uploaded under src/ptb_xl/ instructions of how to get the data
