### ISSUE TITLE
Can you provide more detailed code running instructions? I think this can help more newcomers who have just entered this field. Thank you for your contribution to this field.

### ISSUE THREAD

**Issue by finger-monkey** [AI4HealthUOL/SSSD-ECG#20]

**Comment by finger-monkey** [comment]
In a standard github open source project, it often includes the configuration of the code's operating environment, the source and processing of the data set, the instruction configuration of the training and testing model, etc. I would be very grateful if you could take the time to write a guide.

**Comment by juanlopezcode** [comment]
-please use this requierements.txt file: https://github.com/AI4HealthUOL/SSSD/blob/main/src/requirements.txt
-here is the data preprocessing: https://github.com/AI4HealthUOL/SSSD-ECG/tree/main/src/ptb_xl
-the classifier model is here https://github.com/AI4HealthUOL/ECG-aging, however, this model would achieve better performance which this https://github.com/AI4HealthUOL/MDS-ED/blob/main/src/main_all.py
-once you load the dataset, you have to run the default configuration file, see under line 130 here: https://github.com/AI4HealthUOL/SSSD-ECG/blob/main/src/sssd/train.py

hope it helps
Juan
