### ISSUE TITLE
No module named 'clinical_ts.stratify'

### ISSUE THREAD

**Issue by XLIU430** [AI4HealthUOL/SSSD-ECG#3]
When I run the jupyter notebook 'ecg_data_preprocessing.ipynb'. There is an error in ptb_xl/clinical_ts/ecg_utils.py:31. Which is the 'from .stratify import stratify,stratify_batched'

**Comment by juanlopezcode** [comment]
Hello @XLIU430, you are right, there was missing a stratify.py file. I have added it. It should run now.
