### ISSUE TITLE
Failure to train model on cpu

### ISSUE THREAD

**Issue by bigQY** [AI4HealthUOL/SSSD-ECG#8]
I adjusted the running environment of the code from cuda to cpu and found that the model doesn't run properly

The grad of the calculated loss was none, and after optimiser.step(), the parameters of the model changed to nan, and the training could not be continued.
![image](https://github.com/AI4HealthUOL/SSSD-ECG/assets/52437374/e3c5f379-6bc2-4843-8f61-a81d06a18164)

Can you help me with this or May I ask what kind of environment you have over there, including python and pytorch versions, hardware informations, etc.?

**Comment by juanlopezcode** [comment]
hey, pytorch 1.13.0, python 3.10.8, gpu a30, cuda version 11.6

**Comment by bigQY** [comment]
I have run the model successfully on cuda, thanks for your help!

**Comment by Yang-I-Lin** [comment]
> I have run the model successfully on cuda, thanks for your help!

Hi! I'm new to python and really interested in this article. However,  I'm struggling on setting up the environment lease days. Can you post the requirements.txt of this project?

您好，最近在尝试建立用于此专案的虚拟环境，不过我一直建不太起来，请问您方便提供 requirements.txt 吗? 万分感激!
